---
- name: Update system
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  ansible.builtin.package:
    name:
      - gimp
      - podman
      - v4l2loopback-dkms
      - linux-headers
      - ffmpeg
      - qt6-wayland
      - bluez
      - bluez-utils
      - libreoffice-still
      - fzf
      - fuse2
      - restic
      - go
      - zsh
      - git
      - tmux
      - bat
      - unzip
      - ripgrep
      - wget
      - zoxide
      - exa
      - rclone
      - ttf-jetbrains-mono-nerd
      - ttf-iosevkaterm-nerd
      - mpv
      - wl-clipboard
      - btop
      - syncthing
      - libvirt
      - dnsmasq
      - openbsd-netcat
      - virt-manager
      - qemu-full
      - dmidecode
    state: present

- name: Install yay using makepkg if it isn't installed already
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become: false

- name: Install packages using AUR
  become: false
  kewlfft.aur.aur:
    use: yay
    name:
      - ventoy-bin
      - google-chrome
      - librewolf-bin
      - infisical-bin

- name: Update homebrew and upgrade all packages
  become: false
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- become: false
  community.general.homebrew_tap:
    name:
      - go-task/tap
      - hashicorp/tap
      - derailed/k9s
    state: present

- become: false
  community.general.homebrew:
    name:
    - oci-cli
    - butane
    - kubectl
    - helm
    - go-task/tap/go-task
    - hashicorp/tap/terraform
    - hashicorp/tap/packer
    - derailed/k9s/k9s
    state: present

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.github.iwalton3.jellyfin-media-player
      - tv.kodi.Kodi
      - dev.vencord.Vesktop
      - org.localsend.localsend_app
      - org.mozilla.Thunderbird
      - com.stremio.Stremio
      - com.obsproject.Studio
      - org.sqlitebrowser.sqlitebrowser
      - md.obsidian.Obsidian
      - com.github.skylot.jadx
      - org.ghidra_sre.Ghidra
      - org.telegram.desktop
    state: present

- name: Change user shell to zsh
  become: true
  become_user: "{{ ansible_user_id }}"
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Start and enable systemd user services
  become: true
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.systemd_service:
    state: started
    name: ssh-agent.service
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"

- name: Start and enable systemd user services
  become: true
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.systemd_service:
    state: started
    name: syncthing.service
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"

- name: Start and enable systemd services
  become: true
  loop:
  - libvirtd.socket
  - bluetooth.service
  ansible.builtin.systemd_service:
    state: started
    name: "{{ item }}"
    enabled: true
    scope: system

- name: Create dev directories
  loop:
  - "/home/{{ ansible_user_id }}/personal"
  - "/home/{{ ansible_user_id }}/work"
  - "/home/{{ ansible_user_id }}/Re"
  - "/home/{{ ansible_user_id }}/.kube"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
