---
- name: Update system
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  ansible.builtin.package:
    name:
      - fzf
      - go-task
      - fuse2
      - restic
      - go
      - zsh
      - git
      - tmux
      - bat
      - unzip
      - ripgrep
      - wget
      - zoxide
      - exa
      - rclone
      - ttf-jetbrains-mono-nerd
      - ttf-iosevkaterm-nerd
      - mpv
      - wl-clipboard
      - btop
      - syncthing
    state: present

- name: Install yay using makepkg if it isn't installed already
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become: false

- name: Install packages using AUR
  kewlfft.aur.aur:
    use: yay
    name:
      - google-chrome
      - librewolf-bin

- name: Update homebrew and upgrade all packages
  become: false
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- become: false
  community.general.homebrew:
    name:
      - kubectl
      - helm
    state: present

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - org.localsend.localsend_app
      - org.mozilla.Thunderbird
      - com.stremio.Stremio
      - com.obsproject.Studio
      - org.sqlitebrowser.sqlitebrowser
      - md.obsidian.Obsidian
      - com.github.skylot.jadx
    state: present

- name: Change user shell to zsh
  become: true
  become_user: "{{ ansible_user_id }}"
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Start and enable systemd user services
  become: true
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.systemd_service:
    state: started
    name: ssh-agent.service
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"

- name: Start and enable systemd user services
  become: true
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.systemd_service:
    state: started
    name: syncthing.service
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"

- name: Create dev directories
  ansible.builtin.file:
    path:
    - "/home/{{ ansible_user_id }}/personal"
    - "/home/{{ ansible_user_id }}/work"
    state: directory
    mode: '0755'
