---
- name: Update system
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  ansible.builtin.package:
    name:
      - go
      - zsh
      - git
      - tmux
      - bat
      - unzip
      - ripgrep
      - wget
      - zoxide
      - exa
      - rclone
    state: present

- name: Install yay using makepkg if it isn't installed already
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become: false

- name: Install packages using AUR
  kewlfft.aur.aur:
    use: yay
    name:
      - google-chrome

- name: Update homebrew and upgrade all packages
  become: false
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- become: false
  community.general.homebrew:
    name:
      - kubectl
      - helm
    state: present

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - org.localsend.localsend_app
      - org.mozilla.Thunderbird
    state: present

- name: Change user shell to zsh
  become: true
  vars:
    user: "{{ ansible_user_id }}"
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
